<?php
$title = 'Delete';
$this->headTitle($title);
?>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
        <div class="block">
        <div class="block-title">
            <h2><?=$title?></h2>
        </div>
    
        <p>Are you sure that you want to <code>DELETE</code> <?=$entity->getTitle()?></p>
        <form action="" method="post">
        <input class="btn btn-primary" type="submit" name="delete" value="Yes" />
            <input class="btn btn-warning"  type="submit" name="delete" value="No" />
            <br /><br />
        </form>
		</div>
    </div>
</div>