<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action',$this->url('admin/attachment', array('action' => 'json-edit'), array('query' => array('pageid' => $entity->getPage()->getId(), 'file' => $entity->getName())) ));
?>
<?=$this->form()->openTag($form)?>
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
<h4 class="modal-title" id="myModalLabel">Editing <?=$entity->getName()?></h4>
</div>
<div class="modal-body">
<center>
<img class="img-responsive" src="<?=$entity->getPath()?>" />
</center>
<?=$this->formRow($form->get('attachment')->get('title'))?>
<?=$this->formRow($form->get('attachment')->get('description'))?>

</div>
<div class="modal-footer">
<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
<button type="submit" class="btn btn-primary">Save changes</button>
</div>
<?=$this->form()->closeTag()?>